### ISSUE TITLE
Docker image not configurable

### ISSUE THREAD

**Issue by Philippluca** [CenaFood/swiper.backend#5]
Add possability to configure path and Host-name like in appsettings.json
E.g:
```json
  "Storage": {
    "ImageFolder": "C:\\appdire\\wwww\\images"
  },
  "Hosting": {
    "HostingUri": "http://localhost:51800",
    "ImageHostFolder": "/images"
  },
```

**Comment by SyleKu** [comment]
**Note: Not yet tested!**
-----------------------------------------------------------------

**Pass arguments, when you build an image:**
https://stackoverflow.com/questions/43654656/dockerfile-if-else-condition-with-external-arguments


**This is how you add multiple arguments:**
https://stackoverflow.com/questions/42297387/docker-build-with-build-arg-with-multiple-arguments



**Example:**
`docker build --build-arg HTTP_PROXY=http://10.20.30.2:1234 . `

**It would probably be something like this:**
`docker build --build-arg IMAGE_FOLDER="C:\\my\\path\\to\\images" --build-arg HOSTING_URI="http://localhost:51800"  . `

-----------------------------------------------------------------

**In Dockerfile should be something like this:**

https://docs.docker.com/engine/reference/builder/#using-arg-variables

**Example:**
`docker build --build-arg CONT_IMG_VER=v2.0.1 .`


```
1 FROM ubuntu
2 ARG CONT_IMG_VER
3 ENV CONT_IMG_VER ${CONT_IMG_VER:-v1.0.0}
4 RUN echo $CONT_IMG_VER
```

**For Cena:**
`docker build --build-arg IMAGE_FOLDER="C:\\my\\path\\to\\images" --build-arg HOSTING_URI="http://localhost:51800"  . `

```
1 FROM ubuntu
2 ARG IMAGE_FOLDER
3 ARG HOSTING_URI
4 RUN echo $IMAGE_FOLDER
5 RUN echo $HOSTING_URI
```

**Comment by Philippluca** [comment]
Solved with IOptions and docker_compose file.
https://www.scottbrady91.com/Docker/ASPNET-Core-and-Docker-Environment-Variables
